// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/services/stories/story_creation_approval_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i12;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_core/firebase_core.dart' as _i4;
import 'package:firebase_storage/firebase_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:talia/models/story.dart' as _i7;
import 'package:talia/services/stories/managers/story_cache_manager.dart'
    as _i9;
import 'package:talia/services/stories/managers/story_upload_manager.dart'
    as _i10;
import 'package:talia/services/stories/repositories/contact_repository.dart'
    as _i8;
import 'package:talia/services/stories/repositories/story_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullMetadata_2 extends _i1.SmartFake implements _i3.FullMetadata {
  _FakeFullMetadata_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_3 extends _i1.SmartFake implements _i4.FirebaseApp {
  _FakeFirebaseApp_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettings_4 extends _i1.SmartFake implements _i2.Settings {
  _FakeSettings_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_5<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWriteBatch_6 extends _i1.SmartFake implements _i2.WriteBatch {
  _FakeWriteBatch_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoadBundleTask_7 extends _i1.SmartFake
    implements _i2.LoadBundleTask {
  _FakeLoadBundleTask_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuerySnapshot_8<T1 extends Object?> extends _i1.SmartFake
    implements _i2.QuerySnapshot<T1> {
  _FakeQuerySnapshot_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQuery_9<T extends Object?> extends _i1.SmartFake
    implements _i2.Query<T> {
  _FakeQuery_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_10<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_11<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoryRepository extends _i1.Mock implements _i6.StoryRepository {
  MockStoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i5.Future<_i7.Story?> getById(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [storyId]),
            returnValue: _i5.Future<_i7.Story?>.value(),
          )
          as _i5.Future<_i7.Story?>);

  @override
  _i5.Future<void> create(_i7.Story? story) =>
      (super.noSuchMethod(
            Invocation.method(#create, [story]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> update(String? storyId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#update, [storyId, data]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [storyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.Story>> getByUserId(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getByUserId, [userId]),
            returnValue: _i5.Future<List<_i7.Story>>.value(<_i7.Story>[]),
          )
          as _i5.Future<List<_i7.Story>>);

  @override
  _i5.Stream<List<_i7.Story>> getByUserIdStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getByUserIdStream, [userId]),
            returnValue: _i5.Stream<List<_i7.Story>>.empty(),
          )
          as _i5.Stream<List<_i7.Story>>);

  @override
  _i5.Future<List<_i7.Story>> getByUserIds(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getByUserIds, [userIds]),
            returnValue: _i5.Future<List<_i7.Story>>.value(<_i7.Story>[]),
          )
          as _i5.Future<List<_i7.Story>>);

  @override
  _i5.Stream<List<_i7.Story>> getByUserIdsStream(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#getByUserIdsStream, [userIds]),
            returnValue: _i5.Stream<List<_i7.Story>>.empty(),
          )
          as _i5.Stream<List<_i7.Story>>);

  @override
  _i5.Stream<List<_i7.Story>> getPendingForParent(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingForParent, [parentId]),
            returnValue: _i5.Stream<List<_i7.Story>>.empty(),
          )
          as _i5.Stream<List<_i7.Story>>);

  @override
  _i5.Stream<List<_i7.Story>> getApprovedByParent(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getApprovedByParent, [parentId]),
            returnValue: _i5.Stream<List<_i7.Story>>.empty(),
          )
          as _i5.Stream<List<_i7.Story>>);

  @override
  _i5.Stream<List<_i7.Story>> getRejectedByParent(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getRejectedByParent, [parentId]),
            returnValue: _i5.Stream<List<_i7.Story>>.empty(),
          )
          as _i5.Stream<List<_i7.Story>>);

  @override
  _i5.Future<List<_i7.Story>> getViewedByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getViewedByUser, [userId]),
            returnValue: _i5.Future<List<_i7.Story>>.value(<_i7.Story>[]),
          )
          as _i5.Future<List<_i7.Story>>);

  @override
  _i5.Stream<List<_i7.Story>> getViewedByUserStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getViewedByUserStream, [userId]),
            returnValue: _i5.Stream<List<_i7.Story>>.empty(),
          )
          as _i5.Stream<List<_i7.Story>>);

  @override
  _i5.Future<List<_i7.Story>> getUnviewedFromContacts(
    String? userId,
    List<String>? contactIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnviewedFromContacts, [userId, contactIds]),
            returnValue: _i5.Future<List<_i7.Story>>.value(<_i7.Story>[]),
          )
          as _i5.Future<List<_i7.Story>>);

  @override
  _i5.Stream<List<_i7.Story>> getUnviewedFromContactsStream(
    String? userId,
    List<String>? contactIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnviewedFromContactsStream, [
              userId,
              contactIds,
            ]),
            returnValue: _i5.Stream<List<_i7.Story>>.empty(),
          )
          as _i5.Stream<List<_i7.Story>>);

  @override
  _i5.Future<void> markAsViewed(String? storyId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsViewed, [storyId, userId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> approve(
    String? storyId,
    String? approvedBy, {
    String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #approve,
              [storyId, approvedBy],
              {#message: message},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reject(
    String? storyId,
    String? rejectedBy, {
    String? reason,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reject,
              [storyId, rejectedBy],
              {#reason: reason},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cleanupExpiredStories() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupExpiredStories, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRepository extends _i1.Mock implements _i8.ContactRepository {
  MockContactRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get cacheDuration =>
      (super.noSuchMethod(
            Invocation.getter(#cacheDuration),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#cacheDuration),
            ),
          )
          as Duration);

  @override
  _i5.Future<Set<String>> getContactIds() =>
      (super.noSuchMethod(
            Invocation.method(#getContactIds, []),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  void invalidateContactsCache() => super.noSuchMethod(
    Invocation.method(#invalidateContactsCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Set<String>> getLinkedParents(String? childId) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedParents, [childId]),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Future<Set<String>> getLinkedChildren(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedChildren, [parentId]),
            returnValue: _i5.Future<Set<String>>.value(<String>{}),
          )
          as _i5.Future<Set<String>>);

  @override
  _i5.Stream<Set<String>> getApprovedContactsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getApprovedContactsStream, []),
            returnValue: _i5.Stream<Set<String>>.empty(),
          )
          as _i5.Stream<Set<String>>);

  @override
  _i5.Future<Map<String, Set<String>>> getBatchLinkedParents(
    List<String>? childIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getBatchLinkedParents, [childIds]),
            returnValue: _i5.Future<Map<String, Set<String>>>.value(
              <String, Set<String>>{},
            ),
          )
          as _i5.Future<Map<String, Set<String>>>);

  @override
  _i5.Stream<Set<String>> getLinkedChildrenStream(String? parentId) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedChildrenStream, [parentId]),
            returnValue: _i5.Stream<Set<String>>.empty(),
          )
          as _i5.Stream<Set<String>>);

  @override
  _i5.Stream<Set<String>> getLinkedParentsStream(String? childId) =>
      (super.noSuchMethod(
            Invocation.method(#getLinkedParentsStream, [childId]),
            returnValue: _i5.Stream<Set<String>>.empty(),
          )
          as _i5.Stream<Set<String>>);

  @override
  _i5.Future<Map<String, dynamic>?> getUserInfo(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserInfo, [userId]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<Map<String, Map<String, dynamic>>> getUsersInfo(
    List<String>? userIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersInfo, [userIds]),
            returnValue: _i5.Future<Map<String, Map<String, dynamic>>>.value(
              <String, Map<String, dynamic>>{},
            ),
          )
          as _i5.Future<Map<String, Map<String, dynamic>>>);

  @override
  _i5.Future<String?> getUserRole(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserRole, [userId]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<bool> isInWhitelist(String? userId, String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#isInWhitelist, [userId, targetUserId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StoryCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoryCacheManager extends _i1.Mock implements _i9.StoryCacheManager {
  MockStoryCacheManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i7.UserStories>> get cacheChangesStream =>
      (super.noSuchMethod(
            Invocation.getter(#cacheChangesStream),
            returnValue: _i5.Stream<List<_i7.UserStories>>.empty(),
          )
          as _i5.Stream<List<_i7.UserStories>>);

  @override
  List<_i7.UserStories> getCachedStories() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedStories, []),
            returnValue: <_i7.UserStories>[],
          )
          as List<_i7.UserStories>);

  @override
  void updateCache(List<_i7.UserStories>? stories) => super.noSuchMethod(
    Invocation.method(#updateCache, [stories]),
    returnValueForMissingStub: null,
  );

  @override
  bool isCacheValid() =>
      (super.noSuchMethod(
            Invocation.method(#isCacheValid, []),
            returnValue: false,
          )
          as bool);

  @override
  void invalidateCache() => super.noSuchMethod(
    Invocation.method(#invalidateCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void addOptimisticStory(String? userId, _i7.Story? story) =>
      super.noSuchMethod(
        Invocation.method(#addOptimisticStory, [userId, story]),
        returnValueForMissingStub: null,
      );

  @override
  void updateOptimisticStory(
    String? userId,
    String? storyId,
    _i7.Story? updatedStory,
  ) => super.noSuchMethod(
    Invocation.method(#updateOptimisticStory, [userId, storyId, updatedStory]),
    returnValueForMissingStub: null,
  );

  @override
  void removeOptimisticStory(String? userId, String? storyId) =>
      super.noSuchMethod(
        Invocation.method(#removeOptimisticStory, [userId, storyId]),
        returnValueForMissingStub: null,
      );

  @override
  void clearOptimisticCache() => super.noSuchMethod(
    Invocation.method(#clearOptimisticCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeExpiredStories() => super.noSuchMethod(
    Invocation.method(#removeExpiredStories, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeStoriesByUserId(String? userId) => super.noSuchMethod(
    Invocation.method(#removeStoriesByUserId, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateStoryStatus(String? storyId, _i7.StoryStatus? newStatus) =>
      super.noSuchMethod(
        Invocation.method(#updateStoryStatus, [storyId, newStatus]),
        returnValueForMissingStub: null,
      );

  @override
  void removeStoryById(String? storyId) => super.noSuchMethod(
    Invocation.method(#removeStoryById, [storyId]),
    returnValueForMissingStub: null,
  );

  @override
  void addUserStories(_i7.UserStories? userStories) => super.noSuchMethod(
    Invocation.method(#addUserStories, [userStories]),
    returnValueForMissingStub: null,
  );

  @override
  List<_i7.UserStories> deduplicateStories(List<_i7.UserStories>? stories) =>
      (super.noSuchMethod(
            Invocation.method(#deduplicateStories, [stories]),
            returnValue: <_i7.UserStories>[],
          )
          as List<_i7.UserStories>);

  @override
  List<_i7.UserStories> sortStoriesByPriority(List<_i7.UserStories>? stories) =>
      (super.noSuchMethod(
            Invocation.method(#sortStoriesByPriority, [stories]),
            returnValue: <_i7.UserStories>[],
          )
          as List<_i7.UserStories>);

  @override
  Map<String, dynamic> getMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getMetrics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  double getCacheHitRate() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheHitRate, []),
            returnValue: 0.0,
          )
          as double);

  @override
  void resetMetrics() => super.noSuchMethod(
    Invocation.method(#resetMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StoryUploadManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoryUploadManager extends _i1.Mock
    implements _i10.StoryUploadManager {
  MockStoryUploadManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> uploadStoryMedia({
    required String? filePath,
    required String? storyId,
    required String? userId,
    dynamic Function(double)? onProgressUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadStoryMedia, [], {
              #filePath: filePath,
              #storyId: storyId,
              #userId: userId,
              #onProgressUpdate: onProgressUpdate,
            }),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#uploadStoryMedia, [], {
                  #filePath: filePath,
                  #storyId: storyId,
                  #userId: userId,
                  #onProgressUpdate: onProgressUpdate,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String> uploadWithRetry({
    required String? filePath,
    required String? storyId,
    required String? userId,
    dynamic Function(double)? onProgressUpdate,
    int? maxRetries = 3,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadWithRetry, [], {
              #filePath: filePath,
              #storyId: storyId,
              #userId: userId,
              #onProgressUpdate: onProgressUpdate,
              #maxRetries: maxRetries,
            }),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#uploadWithRetry, [], {
                  #filePath: filePath,
                  #storyId: storyId,
                  #userId: userId,
                  #onProgressUpdate: onProgressUpdate,
                  #maxRetries: maxRetries,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> cancelUpload(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelUpload, [storyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> pauseUpload(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseUpload, [storyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> resumeUpload(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeUpload, [storyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<double>? getProgressStream(String? storyId) =>
      (super.noSuchMethod(Invocation.method(#getProgressStream, [storyId]))
          as _i5.Stream<double>?);

  @override
  bool isUploadActive(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#isUploadActive, [storyId]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.TaskState? getUploadState(String? storyId) =>
      (super.noSuchMethod(Invocation.method(#getUploadState, [storyId]))
          as _i3.TaskState?);

  @override
  _i5.Future<void> deleteStoryMedia(String? downloadUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStoryMedia, [downloadUrl]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> copyFileForReply({
    required String? originalUrl,
    required String? newStoryId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyFileForReply, [], {
              #originalUrl: originalUrl,
              #newStoryId: newStoryId,
              #userId: userId,
            }),
            returnValue: _i5.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#copyFileForReply, [], {
                  #originalUrl: originalUrl,
                  #newStoryId: newStoryId,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<_i3.FullMetadata> getFileMetadata(String? downloadUrl) =>
      (super.noSuchMethod(
            Invocation.method(#getFileMetadata, [downloadUrl]),
            returnValue: _i5.Future<_i3.FullMetadata>.value(
              _FakeFullMetadata_2(
                this,
                Invocation.method(#getFileMetadata, [downloadUrl]),
              ),
            ),
          )
          as _i5.Future<_i3.FullMetadata>);

  @override
  _i5.Future<List<String>> uploadMultipleFiles({
    required List<String>? filePaths,
    required String? storyId,
    required String? userId,
    dynamic Function(String, double)? onProgressUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadMultipleFiles, [], {
              #filePaths: filePaths,
              #storyId: storyId,
              #userId: userId,
              #onProgressUpdate: onProgressUpdate,
            }),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<void> cancelAllUploads() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAllUploads, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  int getPendingUploadsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingUploadsCount, []),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, dynamic> getMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getMetrics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void resetMetrics() => super.noSuchMethod(
    Invocation.method(#resetMetrics, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, Map<String, dynamic>> getActiveUploadsInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveUploadsInfo, []),
            returnValue: <String, Map<String, dynamic>>{},
          )
          as Map<String, Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirebaseFirestore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFirestore extends _i1.Mock implements _i2.FirebaseFirestore {
  MockFirebaseFirestore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_3(this, Invocation.getter(#app)),
          )
          as _i4.FirebaseApp);

  @override
  String get databaseId =>
      (super.noSuchMethod(
            Invocation.getter(#databaseId),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.getter(#databaseId),
            ),
          )
          as String);

  @override
  _i2.Settings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeSettings_4(this, Invocation.getter(#settings)),
          )
          as _i2.Settings);

  @override
  set app(_i4.FirebaseApp? value) => super.noSuchMethod(
    Invocation.setter(#app, value),
    returnValueForMissingStub: null,
  );

  @override
  set databaseId(String? value) => super.noSuchMethod(
    Invocation.setter(#databaseId, value),
    returnValueForMissingStub: null,
  );

  @override
  set settings(_i2.Settings? settings) => super.noSuchMethod(
    Invocation.setter(#settings, settings),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i2.CollectionReference<Map<String, dynamic>> collection(
    String? collectionPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#collection, [collectionPath]),
            returnValue: _FakeCollectionReference_5<Map<String, dynamic>>(
              this,
              Invocation.method(#collection, [collectionPath]),
            ),
          )
          as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.WriteBatch batch() =>
      (super.noSuchMethod(
            Invocation.method(#batch, []),
            returnValue: _FakeWriteBatch_6(this, Invocation.method(#batch, [])),
          )
          as _i2.WriteBatch);

  @override
  _i5.Future<void> clearPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#clearPersistence, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.LoadBundleTask loadBundle(_i12.Uint8List? bundle) =>
      (super.noSuchMethod(
            Invocation.method(#loadBundle, [bundle]),
            returnValue: _FakeLoadBundleTask_7(
              this,
              Invocation.method(#loadBundle, [bundle]),
            ),
          )
          as _i2.LoadBundleTask);

  @override
  void useFirestoreEmulator(
    String? host,
    int? port, {
    bool? sslEnabled = false,
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFirestoreEmulator,
      [host, port],
      {#sslEnabled: sslEnabled, #automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i2.QuerySnapshot<T>> namedQueryWithConverterGet<T>(
    String? name, {
    _i2.GetOptions? options = const _i2.GetOptions(),
    required _i2.FromFirestore<T>? fromFirestore,
    required _i2.ToFirestore<T>? toFirestore,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #namedQueryWithConverterGet,
              [name],
              {
                #options: options,
                #fromFirestore: fromFirestore,
                #toFirestore: toFirestore,
              },
            ),
            returnValue: _i5.Future<_i2.QuerySnapshot<T>>.value(
              _FakeQuerySnapshot_8<T>(
                this,
                Invocation.method(
                  #namedQueryWithConverterGet,
                  [name],
                  {
                    #options: options,
                    #fromFirestore: fromFirestore,
                    #toFirestore: toFirestore,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.QuerySnapshot<T>>);

  @override
  _i5.Future<_i2.QuerySnapshot<Map<String, dynamic>>> namedQueryGet(
    String? name, {
    _i2.GetOptions? options = const _i2.GetOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#namedQueryGet, [name], {#options: options}),
            returnValue:
                _i5.Future<_i2.QuerySnapshot<Map<String, dynamic>>>.value(
                  _FakeQuerySnapshot_8<Map<String, dynamic>>(
                    this,
                    Invocation.method(
                      #namedQueryGet,
                      [name],
                      {#options: options},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.QuerySnapshot<Map<String, dynamic>>>);

  @override
  _i2.Query<Map<String, dynamic>> collectionGroup(String? collectionPath) =>
      (super.noSuchMethod(
            Invocation.method(#collectionGroup, [collectionPath]),
            returnValue: _FakeQuery_9<Map<String, dynamic>>(
              this,
              Invocation.method(#collectionGroup, [collectionPath]),
            ),
          )
          as _i2.Query<Map<String, dynamic>>);

  @override
  _i5.Future<void> disableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#disableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i2.DocumentReference<Map<String, dynamic>> doc(String? documentPath) =>
      (super.noSuchMethod(
            Invocation.method(#doc, [documentPath]),
            returnValue: _FakeDocumentReference_10<Map<String, dynamic>>(
              this,
              Invocation.method(#doc, [documentPath]),
            ),
          )
          as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i5.Future<void> enableNetwork() =>
      (super.noSuchMethod(
            Invocation.method(#enableNetwork, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<void> snapshotsInSync() =>
      (super.noSuchMethod(
            Invocation.method(#snapshotsInSync, []),
            returnValue: _i5.Stream<void>.empty(),
          )
          as _i5.Stream<void>);

  @override
  _i5.Future<T> runTransaction<T>(
    _i2.TransactionHandler<T>? transactionHandler, {
    Duration? timeout = const Duration(seconds: 30),
    int? maxAttempts = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runTransaction,
              [transactionHandler],
              {#timeout: timeout, #maxAttempts: maxAttempts},
            ),
            returnValue:
                _i11.ifNotNull(
                  _i11.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runTransaction,
                      [transactionHandler],
                      {#timeout: timeout, #maxAttempts: maxAttempts},
                    ),
                  ),
                  (T v) => _i5.Future<T>.value(v),
                ) ??
                _FakeFuture_11<T>(
                  this,
                  Invocation.method(
                    #runTransaction,
                    [transactionHandler],
                    {#timeout: timeout, #maxAttempts: maxAttempts},
                  ),
                ),
          )
          as _i5.Future<T>);

  @override
  _i5.Future<void> terminate() =>
      (super.noSuchMethod(
            Invocation.method(#terminate, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> waitForPendingWrites() =>
      (super.noSuchMethod(
            Invocation.method(#waitForPendingWrites, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setIndexConfigurationFromJSON(String? json) =>
      (super.noSuchMethod(
            Invocation.method(#setIndexConfigurationFromJSON, [json]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
