// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/services/data_management_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:talia/services/data_management_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DataManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataManagementService extends _i1.Mock
    implements _i2.DataManagementService {
  MockDataManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> initialize({bool? enableAutoCleanup = true}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #enableAutoCleanup: enableAutoCleanup,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> performAutomaticCleanup() =>
      (super.noSuchMethod(
            Invocation.method(#performAutomaticCleanup, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> cleanOldMessages() =>
      (super.noSuchMethod(
            Invocation.method(#cleanOldMessages, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> cleanOldMedia() =>
      (super.noSuchMethod(
            Invocation.method(#cleanOldMedia, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> cleanOldLocations() =>
      (super.noSuchMethod(
            Invocation.method(#cleanOldLocations, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> cleanOldEmergencies() =>
      (super.noSuchMethod(
            Invocation.method(#cleanOldEmergencies, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<int> cleanLocalCache() =>
      (super.noSuchMethod(
            Invocation.method(#cleanLocalCache, []),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> archiveConversation(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#archiveConversation, [chatId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unarchiveConversation(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#unarchiveConversation, [chatId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> exportUserData() =>
      (super.noSuchMethod(
            Invocation.method(#exportUserData, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> requestAccountDeletion() =>
      (super.noSuchMethod(
            Invocation.method(#requestAccountDeletion, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelAccountDeletion() =>
      (super.noSuchMethod(
            Invocation.method(#cancelAccountDeletion, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAccountPermanently() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccountPermanently, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> getDataUsageStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDataUsageStats, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
