// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/services/offline_queue_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:talia/services/offline_queue_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OfflineQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineQueueService extends _i1.Mock
    implements _i2.OfflineQueueService {
  MockOfflineQueueService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get pendingOperationsCount =>
      (super.noSuchMethod(
            Invocation.getter(#pendingOperationsCount),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasPendingOperations =>
      (super.noSuchMethod(
            Invocation.getter(#hasPendingOperations),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> enqueueOperation({
    required String? type,
    required Map<String, dynamic>? data,
    int? priority = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enqueueOperation, [], {
              #type: type,
              #data: data,
              #priority: priority,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#enqueueOperation, [], {
                  #type: type,
                  #data: data,
                  #priority: priority,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> syncPendingOperations() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingOperations, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<Map<dynamic, dynamic>> getPendingOperations() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOperations, []),
            returnValue: <Map<dynamic, dynamic>>[],
          )
          as List<Map<dynamic, dynamic>>);

  @override
  _i3.Future<void> clearQueue() =>
      (super.noSuchMethod(
            Invocation.method(#clearQueue, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelOperation(String? operationId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelOperation, [operationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
