// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/services/story_service_refactored_mocked_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:talia/models/story.dart' as _i6;
import 'package:talia/services/stories/managers/story_cache_manager.dart'
    as _i2;
import 'package:talia/services/stories/managers/story_stream_manager.dart'
    as _i3;
import 'package:talia/services/stories/story_orchestrator.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeStoryCacheManager_0 extends _i1.SmartFake
    implements _i2.StoryCacheManager {
  _FakeStoryCacheManager_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStoryStreamManager_1 extends _i1.SmartFake
    implements _i3.StoryStreamManager {
  _FakeStoryStreamManager_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [StoryOrchestrator].
///
/// See the documentation for Mockito's code generation for more information.
class MockStoryOrchestrator extends _i1.Mock implements _i4.StoryOrchestrator {
  MockStoryOrchestrator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.UserStories>> get storiesFromCache =>
      (super.noSuchMethod(
            Invocation.getter(#storiesFromCache),
            returnValue: _i5.Stream<List<_i6.UserStories>>.empty(),
          )
          as _i5.Stream<List<_i6.UserStories>>);

  @override
  _i2.StoryCacheManager get cacheManagerForTesting =>
      (super.noSuchMethod(
            Invocation.getter(#cacheManagerForTesting),
            returnValue: _FakeStoryCacheManager_0(
              this,
              Invocation.getter(#cacheManagerForTesting),
            ),
          )
          as _i2.StoryCacheManager);

  @override
  _i3.StoryStreamManager get streamManagerForTesting =>
      (super.noSuchMethod(
            Invocation.getter(#streamManagerForTesting),
            returnValue: _FakeStoryStreamManager_1(
              this,
              Invocation.getter(#streamManagerForTesting),
            ),
          )
          as _i3.StoryStreamManager);

  @override
  _i5.Future<String> createStory({
    required String? mediaType,
    required String? mediaPath,
    String? text,
    Map<String, dynamic>? filter,
    dynamic Function(String, double)? onProgressUpdate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createStory, [], {
              #mediaType: mediaType,
              #mediaPath: mediaPath,
              #text: text,
              #filter: filter,
              #onProgressUpdate: onProgressUpdate,
            }),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createStory, [], {
                  #mediaType: mediaType,
                  #mediaPath: mediaPath,
                  #text: text,
                  #filter: filter,
                  #onProgressUpdate: onProgressUpdate,
                }),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Stream<List<_i6.UserStories>> getStoriesFromWhitelist() =>
      (super.noSuchMethod(
            Invocation.method(#getStoriesFromWhitelist, []),
            returnValue: _i5.Stream<List<_i6.UserStories>>.empty(),
          )
          as _i5.Stream<List<_i6.UserStories>>);

  @override
  List<_i6.UserStories> getCachedStories() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedStories, []),
            returnValue: <_i6.UserStories>[],
          )
          as List<_i6.UserStories>);

  @override
  _i5.Future<void> markStoryAsViewed(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#markStoryAsViewed, [storyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteStory(String? storyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteStory, [storyId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> approveStory(String? storyId, {String? message}) =>
      (super.noSuchMethod(
            Invocation.method(#approveStory, [storyId], {#message: message}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> rejectStory(String? storyId, {String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#rejectStory, [storyId], {#reason: reason}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i6.Story>> getPendingStoriesForParent() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingStoriesForParent, []),
            returnValue: _i5.Stream<List<_i6.Story>>.empty(),
          )
          as _i5.Stream<List<_i6.Story>>);

  @override
  _i5.Stream<List<_i6.Story>> getApprovedStoriesForParent() =>
      (super.noSuchMethod(
            Invocation.method(#getApprovedStoriesForParent, []),
            returnValue: _i5.Stream<List<_i6.Story>>.empty(),
          )
          as _i5.Stream<List<_i6.Story>>);

  @override
  _i5.Future<void> replyToStory({
    required String? storyId,
    required String? replyText,
    String? replyMediaPath,
    String? replyMediaType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#replyToStory, [], {
              #storyId: storyId,
              #replyText: replyText,
              #replyMediaPath: replyMediaPath,
              #replyMediaType: replyMediaType,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startBackgroundProcesses() =>
      (super.noSuchMethod(
            Invocation.method(#startBackgroundProcesses, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void stopBackgroundProcesses() => super.noSuchMethod(
    Invocation.method(#stopBackgroundProcesses, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> cleanupExpiredStories() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupExpiredStories, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> forceRefreshCache() =>
      (super.noSuchMethod(
            Invocation.method(#forceRefreshCache, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getPerformanceMetrics() =>
      (super.noSuchMethod(
            Invocation.method(#getPerformanceMetrics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
