// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/services/user_profile_cache_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:talia/services/user_profile_cache_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [UserProfileCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileCacheService extends _i1.Mock
    implements _i2.UserProfileCacheService {
  MockUserProfileCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<Map<String, dynamic>?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> preloadProfiles(List<String>? userIds) =>
      (super.noSuchMethod(
            Invocation.method(#preloadProfiles, [userIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void invalidateUser(String? userId) => super.noSuchMethod(
    Invocation.method(#invalidateUser, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateCachedProfile(String? userId, Map<String, dynamic>? updates) =>
      super.noSuchMethod(
        Invocation.method(#updateCachedProfile, [userId, updates]),
        returnValueForMissingStub: null,
      );

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Stream<_i4.DocumentSnapshot<Object?>> getUserDataStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDataStream, [userId]),
            returnValue: _i3.Stream<_i4.DocumentSnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i4.DocumentSnapshot<Object?>>);

  @override
  Map<String, dynamic> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
