// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/services/video_call_validation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:talia/services/block_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BlockService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlockService extends _i1.Mock implements _i2.BlockService {
  MockBlockService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> blockContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#blockContact, [contactId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> unblockContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#unblockContact, [contactId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> isBlocked(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlocked, [contactId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<bool> isBlockedStream(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlockedStream, [contactId]),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Future<bool> isBlockedBy(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlockedBy, [userId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<bool> isBlockedByStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#isBlockedByStream, [userId]),
            returnValue: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Stream<List<String>> getBlockedContactsStream() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedContactsStream, []),
            returnValue: _i3.Stream<List<String>>.empty(),
          )
          as _i3.Stream<List<String>>);

  @override
  _i3.Future<List<String>> getBlockedContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getBlockedContacts, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<bool> isMutualBlock(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#isMutualBlock, [contactId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
