// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKi6XA5WRCODdiBYKkc5m6CyDojGqWdOY',
    appId: '1:1092721435813:web:8a41b71afe8e688176194c',
    messagingSenderId: '1092721435813',
    projectId: 'talia-staging',
    authDomain: 'talia-staging.firebaseapp.com',
    storageBucket: 'talia-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7UwZDgvbbjDNfIokW5nXdRAWFfQ5SQb8',
    appId: '1:1092721435813:android:e37dde89b87350a876194c',
    messagingSenderId: '1092721435813',
    projectId: 'talia-staging',
    storageBucket: 'talia-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGJfkJIO4jt8ZLtwJ1gT4Cfu3WXjWj2U',
    appId: '1:1092721435813:ios:7dcd6b982ea1386b76194c',
    messagingSenderId: '1092721435813',
    projectId: 'talia-staging',
    storageBucket: 'talia-staging.firebasestorage.app',
    iosBundleId: 'com.talia.chat.staging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXGJfkJIO4jt8ZLtwJ1gT4Cfu3WXjWj2U',
    appId: '1:1092721435813:ios:6b75b20326d2849f76194c',
    messagingSenderId: '1092721435813',
    projectId: 'talia-staging',
    storageBucket: 'talia-staging.firebasestorage.app',
    iosBundleId: 'com.example.talia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKi6XA5WRCODdiBYKkc5m6CyDojGqWdOY',
    appId: '1:1092721435813:web:a3e91777fa30796976194c',
    messagingSenderId: '1092721435813',
    projectId: 'talia-staging',
    authDomain: 'talia-staging.firebaseapp.com',
    storageBucket: 'talia-staging.firebasestorage.app',
  );
}
