// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/screens/common/incoming_call_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:talia/services/video_call_service.dart' as _i2;
import 'package:vibration/vibration.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VideoCallService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoCallService extends _i1.Mock implements _i2.VideoCallService {
  MockVideoCallService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isCameraOff =>
      (super.noSuchMethod(Invocation.getter(#isCameraOff), returnValue: false)
          as bool);

  @override
  bool get isMuted =>
      (super.noSuchMethod(Invocation.getter(#isMuted), returnValue: false)
          as bool);

  @override
  _i3.Future<Map<String, dynamic>> generateAgoraToken(
    String? channelName, {
    int? uid = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateAgoraToken, [channelName], {#uid: uid}),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> initializeAgora({bool? isVideo = true}) =>
      (super.noSuchMethod(
            Invocation.method(#initializeAgora, [], {#isVideo: isVideo}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> initializeAgoraAudio() =>
      (super.noSuchMethod(
            Invocation.method(#initializeAgoraAudio, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> requestPermissions() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermissions, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> joinChannel({
    required String? channelName,
    required String? token,
    required int? uid,
    bool? isVideo = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinChannel, [], {
              #channelName: channelName,
              #token: token,
              #uid: uid,
              #isVideo: isVideo,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> leaveChannel() =>
      (super.noSuchMethod(
            Invocation.method(#leaveChannel, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleMute() =>
      (super.noSuchMethod(
            Invocation.method(#toggleMute, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> toggleCamera() =>
      (super.noSuchMethod(
            Invocation.method(#toggleCamera, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void resetInitialization() => super.noSuchMethod(
    Invocation.method(#resetInitialization, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String> startCall({
    required String? callerId,
    required String? callerName,
    required String? receiverId,
    required String? receiverName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startCall, [], {
              #callerId: callerId,
              #callerName: callerName,
              #receiverId: receiverId,
              #receiverName: receiverName,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#startCall, [], {
                  #callerId: callerId,
                  #callerName: callerName,
                  #receiverId: receiverId,
                  #receiverName: receiverName,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> startAudioCall({
    required String? callerId,
    required String? callerName,
    required String? receiverId,
    required String? receiverName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startAudioCall, [], {
              #callerId: callerId,
              #callerName: callerName,
              #receiverId: receiverId,
              #receiverName: receiverName,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#startAudioCall, [], {
                  #callerId: callerId,
                  #callerName: callerName,
                  #receiverId: receiverId,
                  #receiverName: receiverName,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> startGroupCall({
    required String? callerId,
    required String? callerName,
    required List<String>? participantIds,
    required Map<String, String>? participantNames,
    String? groupId,
    bool? isEmergency = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGroupCall, [], {
              #callerId: callerId,
              #callerName: callerName,
              #participantIds: participantIds,
              #participantNames: participantNames,
              #groupId: groupId,
              #isEmergency: isEmergency,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#startGroupCall, [], {
                  #callerId: callerId,
                  #callerName: callerName,
                  #participantIds: participantIds,
                  #participantNames: participantNames,
                  #groupId: groupId,
                  #isEmergency: isEmergency,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> startGroupAudioCall({
    required String? callerId,
    required String? callerName,
    required List<String>? participantIds,
    required Map<String, String>? participantNames,
    String? groupId,
    bool? isEmergency = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGroupAudioCall, [], {
              #callerId: callerId,
              #callerName: callerName,
              #participantIds: participantIds,
              #participantNames: participantNames,
              #groupId: groupId,
              #isEmergency: isEmergency,
            }),
            returnValue: _i3.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(#startGroupAudioCall, [], {
                  #callerId: callerId,
                  #callerName: callerName,
                  #participantIds: participantIds,
                  #participantNames: participantNames,
                  #groupId: groupId,
                  #isEmergency: isEmergency,
                }),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateParticipantStatus({
    required String? callId,
    required String? userId,
    required String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateParticipantStatus, [], {
              #callId: callId,
              #userId: userId,
              #status: status,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> inviteToOngoingCall({
    required String? callId,
    required String? channelName,
    required String? invitedUserId,
    required String? invitedUserName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#inviteToOngoingCall, [], {
              #callId: callId,
              #channelName: channelName,
              #invitedUserId: invitedUserId,
              #invitedUserName: invitedUserName,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Stream<_i5.QuerySnapshot<Object?>> watchIncomingGroupCalls(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchIncomingGroupCalls, [userId]),
            returnValue: _i3.Stream<_i5.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i3.Future<void> acceptCall(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptCall, [callId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> rejectCall(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectCall, [callId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> endCall(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#endCall, [callId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i5.QuerySnapshot<Object?>> watchIncomingCalls(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchIncomingCalls, [userId]),
            returnValue: _i3.Stream<_i5.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i3.Stream<_i5.DocumentSnapshot<Object?>> watchCallStatus(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCallStatus, [callId]),
            returnValue: _i3.Stream<_i5.DocumentSnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i5.DocumentSnapshot<Object?>>);

  @override
  _i3.Future<Map<String, dynamic>> initiateCall({
    required String? receiverId,
    required String? receiverName,
    required bool? isVideo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initiateCall, [], {
              #receiverId: receiverId,
              #receiverName: receiverName,
              #isVideo: isVideo,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> createMissedCallMessage({
    required String? callerId,
    required String? receiverId,
    required String? callType,
    required String? callId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createMissedCallMessage, [], {
              #callerId: callerId,
              #receiverId: receiverId,
              #callType: callType,
              #callId: callId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<dynamic> import_chatService() =>
      (super.noSuchMethod(
            Invocation.method(#import_chatService, []),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> import_callKitService() =>
      (super.noSuchMethod(
            Invocation.method(#import_callKitService, []),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);
}

/// A class which mocks [Vibration].
///
/// See the documentation for Mockito's code generation for more information.
class MockVibration extends _i1.Mock implements _i6.Vibration {
  MockVibration() {
    _i1.throwOnMissingStub(this);
  }
}
