// Mocks generated by Mockito 5.4.6 from annotations
// in talia/test/integration/video_call_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:talia/services/video_calls/services/call_state_service.dart'
    as _i4;
import 'package:talia/services/video_calls/video_call_orchestrator.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VideoCallOrchestrator].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoCallOrchestrator extends _i1.Mock
    implements _i2.VideoCallOrchestrator {
  MockVideoCallOrchestrator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.CallStateUpdate> get callStateStream =>
      (super.noSuchMethod(
            Invocation.getter(#callStateStream),
            returnValue: _i3.Stream<_i4.CallStateUpdate>.empty(),
          )
          as _i3.Stream<_i4.CallStateUpdate>);

  @override
  _i3.Stream<List<_i4.IncomingCall>> get incomingCallsStream =>
      (super.noSuchMethod(
            Invocation.getter(#incomingCallsStream),
            returnValue: _i3.Stream<List<_i4.IncomingCall>>.empty(),
          )
          as _i3.Stream<List<_i4.IncomingCall>>);

  @override
  bool get isMuted =>
      (super.noSuchMethod(Invocation.getter(#isMuted), returnValue: false)
          as bool);

  @override
  bool get isCameraOff =>
      (super.noSuchMethod(Invocation.getter(#isCameraOff), returnValue: false)
          as bool);

  @override
  bool get isJoined =>
      (super.noSuchMethod(Invocation.getter(#isJoined), returnValue: false)
          as bool);

  @override
  Set<int> get remoteUids =>
      (super.noSuchMethod(Invocation.getter(#remoteUids), returnValue: <int>{})
          as Set<int>);

  @override
  set onConnectionStatusChanged(dynamic Function(String)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onConnectionStatusChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onRemoteUsersChanged(dynamic Function(Set<int>)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onRemoteUsersChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  set onLocalUserJoined(dynamic Function(bool)? value) => super.noSuchMethod(
    Invocation.setter(#onLocalUserJoined, value),
    returnValueForMissingStub: null,
  );

  @override
  set onError(dynamic Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  set onCallEnded(dynamic Function()? value) => super.noSuchMethod(
    Invocation.setter(#onCallEnded, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>> startCall({
    required String? receiverId,
    required String? receiverName,
    required bool? isVideo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startCall, [], {
              #receiverId: receiverId,
              #receiverName: receiverName,
              #isVideo: isVideo,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> acceptCall(String? callId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptCall, [callId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<bool> rejectCall(String? callId, {String? reason = 'declined'}) =>
      (super.noSuchMethod(
            Invocation.method(#rejectCall, [callId], {#reason: reason}),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> endCall() =>
      (super.noSuchMethod(
            Invocation.method(#endCall, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> toggleMute() =>
      (super.noSuchMethod(
            Invocation.method(#toggleMute, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> toggleCamera() =>
      (super.noSuchMethod(
            Invocation.method(#toggleCamera, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> joinExistingChannel({
    required String? channelName,
    required String? token,
    required int? uid,
    required bool? isVideo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#joinExistingChannel, [], {
              #channelName: channelName,
              #token: token,
              #uid: uid,
              #isVideo: isVideo,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void startMonitoringIncomingCalls() => super.noSuchMethod(
    Invocation.method(#startMonitoringIncomingCalls, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopMonitoringIncomingCalls() => super.noSuchMethod(
    Invocation.method(#stopMonitoringIncomingCalls, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<List<_i4.ActiveCall>> getActiveCalls() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveCalls, []),
            returnValue: _i3.Future<List<_i4.ActiveCall>>.value(
              <_i4.ActiveCall>[],
            ),
          )
          as _i3.Future<List<_i4.ActiveCall>>);

  @override
  _i3.Future<bool> hasActiveCalls() =>
      (super.noSuchMethod(
            Invocation.method(#hasActiveCalls, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Stream<_i5.QuerySnapshot<Object?>> watchIncomingCalls(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchIncomingCalls, [userId]),
            returnValue: _i3.Stream<_i5.QuerySnapshot<Object?>>.empty(),
          )
          as _i3.Stream<_i5.QuerySnapshot<Object?>>);

  @override
  _i3.Future<Map<String, dynamic>> startGroupCall({
    required String? groupId,
    required String? groupName,
    required List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGroupCall, [], {
              #groupId: groupId,
              #groupName: groupName,
              #memberIds: memberIds,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> startGroupAudioCall({
    required String? groupId,
    required String? groupName,
    required List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startGroupAudioCall, [], {
              #groupId: groupId,
              #groupName: groupName,
              #memberIds: memberIds,
            }),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  Map<String, dynamic> getDebugInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDebugInfo, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
